### ISSUE TITLE
Cannot start up the project

### ISSUE THREAD

**Issue by Chipcius** [SimplyTechnologies/guidetoiceland#1]
After downloading the code and installing the dependencies I get the following message when trying to run 

```
$ yarn start
yarn start v0.20.3
$ better-npm-run start 
running better-npm-run in /home/andri/guidetoiceland
Executing script: start

to be executed: node server 
Hash: 669bae119ae225b001fb
Version: webpack 2.2.1
Time: 7588ms
                                 Asset     Size  Chunks  Chunk Names
  674f50d287a8c48dc19ba404d20fe713.eot   166 kB          
  912ec66d7572ff821749319396470bde.svg   444 kB          
  b06871f281fee6b241d60582ae9369b9.ttf   166 kB          
af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          
 fee66e712a8a08eef5805a46892932ad.woff    98 kB          
       0.669bae119ae225b001fb.chunk.js   829 kB       0  
          main.669bae119ae225b001fb.js  4.98 MB       1  main
chunk    {0} 0.669bae119ae225b001fb.chunk.js 300 kB {1} [rendered]
  [677] ./client/src/modules/dashboard/Dashboard.container.js 3.91 kB {0} [built]
  [678] ./~/reactstrap/dist/reactstrap.es.js 167 kB {0} [built]
  [679] ./client/src/constants/mockData.js 13 kB {0} [built]
  [680] ./client/src/modules/dashboard/components/GalleryItem/GalleryItem.js 1.81 kB {0} [built]
  [681] ./~/classnames/index.js 1.1 kB {0} [built]
  [682] ./client/src/modules/dashboard/components/FilterButtons/FilterButtons.js 2.79 kB {0} [built]
  [683] ./client/src/modules/dashboard/components/FilterButtons/index.js 612 bytes {0} [built]
  [684] ./client/src/modules/dashboard/components/Gallery/Gallery.js 1.34 kB {0} [built]
  [685] ./client/src/modules/dashboard/components/GalleryItem/index.js 600 bytes {0} [built]
  [686] ./client/src/modules/dashboard/components/index.js 822 bytes {0} [built]
  [687] ./~/lodash.isfunction/index.js 2.13 kB {0} [built]
  [688] ./~/lodash.isobject/index.js 1.14 kB {0} [built]
  [689] ./~/lodash.tonumber/index.js 4 kB {0} [built]
  [691] ./~/react-popper/lib/Arrow.js 2.24 kB {0} [built]
  [695] ./~/react-popper/lib/react-popper.js 744 bytes {0} [built]
     + 4 hidden modules
chunk    {1} main.669bae119ae225b001fb.js (main) 1.79 MB [entry] [rendered]
  [107] ./client/src/router/index.js 431 bytes {1} [built]
  [159] ./~/react-dom/index.js 1.36 kB {1} [built]
  [248] (webpack)/hot/emitter.js 77 bytes {1} [built]
  [249] ./client/src/index.js 977 bytes {1} [built]
  [250] ./~/font-awesome-loader/index.js 102 bytes {1} [built]
  [251] ./~/react-hot-loader/patch.js 41 bytes {1} [built]
  [252] (webpack)-dev-server/client?http://0.0.0.0:3000 5.28 kB {1} [built]
  [253] (webpack)/hot/only-dev-server.js 2.29 kB {1} [built]
  [605] ./~/react-hot-loader/lib/patch.js 209 bytes {1} [built]
  [664] ./~/strip-ansi/index.js 161 bytes {1} [built]
  [665] ./~/bootstrap/dist/css/bootstrap.css 982 bytes {1} [built]
  [666] ./client/styles/main.scss 1.05 kB {1} [built]
  [673] (webpack)-dev-server/client/socket.js 856 bytes {1} [built]
  [675] (webpack)/hot/log-apply-result.js 1.02 kB {1} [built]
  [676] multi webpack-dev-server/client?http://0.0.0.0:3000 webpack/hot/only-dev-server font-awesome-loader react-hot-loader/patch ./src/index.js 76 bytes {1} [built]
     + 662 hidden modules

ERROR in ./~/css-loader!./~/postcss-loader!./~/bootstrap/dist/css/bootstrap.css
Module build failed: BrowserslistError: Unknown browser major
    at error (/home/andri/guidetoiceland/node_modules/browserslist/index.js:37:11)
    at Function.browserslist.checkName (/home/andri/guidetoiceland/node_modules/browserslist/index.js:320:18)
    at Function.select (/home/andri/guidetoiceland/node_modules/browserslist/index.js:438:37)
    at /home/andri/guidetoiceland/node_modules/browserslist/index.js:207:41
    at Array.forEach (native)
    at browserslist (/home/andri/guidetoiceland/node_modules/browserslist/index.js:196:13)
    at Browsers.parse (/home/andri/guidetoiceland/node_modules/autoprefixer/lib/browsers.js:44:14)
    at new Browsers (/home/andri/guidetoiceland/node_modules/autoprefixer/lib/browsers.js:39:28)
    at loadPrefixes (/home/andri/guidetoiceland/node_modules/autoprefixer/lib/autoprefixer.js:56:18)
    at plugin (/home/andri/guidetoiceland/node_modules/autoprefixer/lib/autoprefixer.js:62:18)
    at LazyResult.run (/home/andri/guidetoiceland/node_modules/postcss/lib/lazy-result.js:274:20)
    at LazyResult.asyncTick (/home/andri/guidetoiceland/node_modules/postcss/lib/lazy-result.js:189:32)
    at LazyResult.asyncTick (/home/andri/guidetoiceland/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/home/andri/guidetoiceland/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/home/andri/guidetoiceland/node_modules/postcss/lib/lazy-result.js:201:22)
    at LazyResult.asyncTick (/home/andri/guidetoiceland/node_modules/postcss/lib/lazy-result.js:201:22)
 @ ./~/bootstrap/dist/css/bootstrap.css 4:14-104 13:2-17:4 14:20-110
 @ ./client/src/index.js
 @ multi webpack-dev-server/client?http://0.0.0.0:3000 webpack/hot/only-dev-server font-awesome-loader react-hot-loader/patch ./src/index.js
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  567 kB       0  
    chunk    {0} index.html 541 kB [entry] [rendered]
        [0] ./~/lodash/lodash.js 540 kB {0} [built]
        [1] (webpack)/buildin/global.js 509 bytes {0} [built]
        [2] (webpack)/buildin/module.js 517 bytes {0} [built]
        [3] ./~/html-webpack-plugin/lib/loader.js!./client/index.html 518 bytes {0} [built]
webpack: Failed to compile.
```
node version: v9.2.0
yarn version: 1.3.2

steps to reproduce
```
git clone https://github.com/SimplyTechnologies/guidetoiceland.git
cd guidetoiceland
yarn install
yarn start
```

**Comment by shahen94** [comment]
Hi @Chipcius .
Bootstrap's new version has been released which involves some breaking changes.
I fixed the version in package.json so that it will help us to keep all versions the same in all of our machines.
